// Generated by scripts/generate.mjs from kubernetes-models. Do not edit.
import type { IConfigMap } from "kubernetes-models/v1/ConfigMap";
import type { IEndpoints } from "kubernetes-models/v1/Endpoints";
import type { IEvent } from "kubernetes-models/v1/Event";
import type { ILimitRange } from "kubernetes-models/v1/LimitRange";
import type { INamespace } from "kubernetes-models/v1/Namespace";
import type { INode } from "kubernetes-models/v1/Node";
import type { IPersistentVolume } from "kubernetes-models/v1/PersistentVolume";
import type { IPersistentVolumeClaim } from "kubernetes-models/v1/PersistentVolumeClaim";
import type { IPod } from "kubernetes-models/v1/Pod";
import type { IPodTemplate } from "kubernetes-models/v1/PodTemplate";
import type { IReplicationController } from "kubernetes-models/v1/ReplicationController";
import type { IResourceQuota } from "kubernetes-models/v1/ResourceQuota";
import type { IService } from "kubernetes-models/v1/Service";
import type { IServiceAccount } from "kubernetes-models/v1/ServiceAccount";
import type { IControllerRevision } from "kubernetes-models/apps/v1/ControllerRevision";
import type { IDaemonSet } from "kubernetes-models/apps/v1/DaemonSet";
import type { IDeployment } from "kubernetes-models/apps/v1/Deployment";
import type { IReplicaSet } from "kubernetes-models/apps/v1/ReplicaSet";
import type { IStatefulSet } from "kubernetes-models/apps/v1/StatefulSet";
import type { ICronJob } from "kubernetes-models/batch/v1/CronJob";
import type { IJob } from "kubernetes-models/batch/v1/Job";
import type { IIPAddress } from "kubernetes-models/networking.k8s.io/v1/IPAddress";
import type { IIngress } from "kubernetes-models/networking.k8s.io/v1/Ingress";
import type { IIngressClass } from "kubernetes-models/networking.k8s.io/v1/IngressClass";
import type { INetworkPolicy } from "kubernetes-models/networking.k8s.io/v1/NetworkPolicy";
import type { IServiceCIDR } from "kubernetes-models/networking.k8s.io/v1/ServiceCIDR";
import type { IClusterRole } from "kubernetes-models/rbac.authorization.k8s.io/v1/ClusterRole";
import type { IClusterRoleBinding } from "kubernetes-models/rbac.authorization.k8s.io/v1/ClusterRoleBinding";
import type { IRole } from "kubernetes-models/rbac.authorization.k8s.io/v1/Role";
import type { IRoleBinding } from "kubernetes-models/rbac.authorization.k8s.io/v1/RoleBinding";
import type { IHorizontalPodAutoscaler } from "kubernetes-models/autoscaling/v2/HorizontalPodAutoscaler";
import type { IPodDisruptionBudget } from "kubernetes-models/policy/v1/PodDisruptionBudget";
import type { ICSIDriver } from "kubernetes-models/storage.k8s.io/v1/CSIDriver";
import type { ICSINode } from "kubernetes-models/storage.k8s.io/v1/CSINode";
import type { ICSIStorageCapacity } from "kubernetes-models/storage.k8s.io/v1/CSIStorageCapacity";
import type { IStorageClass } from "kubernetes-models/storage.k8s.io/v1/StorageClass";
import type { IVolumeAttachment } from "kubernetes-models/storage.k8s.io/v1/VolumeAttachment";
import type { IVolumeAttributesClass } from "kubernetes-models/storage.k8s.io/v1/VolumeAttributesClass";
import type { ICustomResourceDefinition } from "kubernetes-models/apiextensions.k8s.io/v1/CustomResourceDefinition";
import { defineBuiltin, definePatch } from "./resource.ts";

export const api = {
  core: {
    v1: {
      ConfigMap: defineBuiltin<IConfigMap>("v1", "ConfigMap"),
      ConfigMapPatch: definePatch<IConfigMap>("v1", "ConfigMap"),
      Endpoints: defineBuiltin<IEndpoints>("v1", "Endpoints"),
      EndpointsPatch: definePatch<IEndpoints>("v1", "Endpoints"),
      Event: defineBuiltin<IEvent>("v1", "Event"),
      EventPatch: definePatch<IEvent>("v1", "Event"),
      LimitRange: defineBuiltin<ILimitRange>("v1", "LimitRange"),
      LimitRangePatch: definePatch<ILimitRange>("v1", "LimitRange"),
      Namespace: defineBuiltin<INamespace>("v1", "Namespace"),
      NamespacePatch: definePatch<INamespace>("v1", "Namespace"),
      Node: defineBuiltin<INode>("v1", "Node"),
      NodePatch: definePatch<INode>("v1", "Node"),
      PersistentVolume: defineBuiltin<IPersistentVolume>(
        "v1",
        "PersistentVolume",
      ),
      PersistentVolumePatch: definePatch<IPersistentVolume>(
        "v1",
        "PersistentVolume",
      ),
      PersistentVolumeClaim: defineBuiltin<IPersistentVolumeClaim>(
        "v1",
        "PersistentVolumeClaim",
      ),
      PersistentVolumeClaimPatch: definePatch<IPersistentVolumeClaim>(
        "v1",
        "PersistentVolumeClaim",
      ),
      Pod: defineBuiltin<IPod>("v1", "Pod"),
      PodPatch: definePatch<IPod>("v1", "Pod"),
      PodTemplate: defineBuiltin<IPodTemplate>("v1", "PodTemplate"),
      PodTemplatePatch: definePatch<IPodTemplate>("v1", "PodTemplate"),
      ReplicationController: defineBuiltin<IReplicationController>(
        "v1",
        "ReplicationController",
      ),
      ReplicationControllerPatch: definePatch<IReplicationController>(
        "v1",
        "ReplicationController",
      ),
      ResourceQuota: defineBuiltin<IResourceQuota>("v1", "ResourceQuota"),
      ResourceQuotaPatch: definePatch<IResourceQuota>("v1", "ResourceQuota"),
      Service: defineBuiltin<IService>("v1", "Service"),
      ServicePatch: definePatch<IService>("v1", "Service"),
      ServiceAccount: defineBuiltin<IServiceAccount>("v1", "ServiceAccount"),
      ServiceAccountPatch: definePatch<IServiceAccount>("v1", "ServiceAccount"),
    },
  },
  apps: {
    v1: {
      ControllerRevision: defineBuiltin<IControllerRevision>(
        "apps/v1",
        "ControllerRevision",
      ),
      ControllerRevisionPatch: definePatch<IControllerRevision>(
        "apps/v1",
        "ControllerRevision",
      ),
      DaemonSet: defineBuiltin<IDaemonSet>("apps/v1", "DaemonSet"),
      DaemonSetPatch: definePatch<IDaemonSet>("apps/v1", "DaemonSet"),
      Deployment: defineBuiltin<IDeployment>("apps/v1", "Deployment"),
      DeploymentPatch: definePatch<IDeployment>("apps/v1", "Deployment"),
      ReplicaSet: defineBuiltin<IReplicaSet>("apps/v1", "ReplicaSet"),
      ReplicaSetPatch: definePatch<IReplicaSet>("apps/v1", "ReplicaSet"),
      StatefulSet: defineBuiltin<IStatefulSet>("apps/v1", "StatefulSet"),
      StatefulSetPatch: definePatch<IStatefulSet>("apps/v1", "StatefulSet"),
    },
  },
  batch: {
    v1: {
      CronJob: defineBuiltin<ICronJob>("batch/v1", "CronJob"),
      CronJobPatch: definePatch<ICronJob>("batch/v1", "CronJob"),
      Job: defineBuiltin<IJob>("batch/v1", "Job"),
      JobPatch: definePatch<IJob>("batch/v1", "Job"),
    },
  },
  networking: {
    v1: {
      IPAddress: defineBuiltin<IIPAddress>("networking.k8s.io/v1", "IPAddress"),
      IPAddressPatch: definePatch<IIPAddress>(
        "networking.k8s.io/v1",
        "IPAddress",
      ),
      Ingress: defineBuiltin<IIngress>("networking.k8s.io/v1", "Ingress"),
      IngressPatch: definePatch<IIngress>("networking.k8s.io/v1", "Ingress"),
      IngressClass: defineBuiltin<IIngressClass>(
        "networking.k8s.io/v1",
        "IngressClass",
      ),
      IngressClassPatch: definePatch<IIngressClass>(
        "networking.k8s.io/v1",
        "IngressClass",
      ),
      NetworkPolicy: defineBuiltin<INetworkPolicy>(
        "networking.k8s.io/v1",
        "NetworkPolicy",
      ),
      NetworkPolicyPatch: definePatch<INetworkPolicy>(
        "networking.k8s.io/v1",
        "NetworkPolicy",
      ),
      ServiceCIDR: defineBuiltin<IServiceCIDR>(
        "networking.k8s.io/v1",
        "ServiceCIDR",
      ),
      ServiceCIDRPatch: definePatch<IServiceCIDR>(
        "networking.k8s.io/v1",
        "ServiceCIDR",
      ),
    },
  },
  rbac: {
    v1: {
      ClusterRole: defineBuiltin<IClusterRole>(
        "rbac.authorization.k8s.io/v1",
        "ClusterRole",
      ),
      ClusterRolePatch: definePatch<IClusterRole>(
        "rbac.authorization.k8s.io/v1",
        "ClusterRole",
      ),
      ClusterRoleBinding: defineBuiltin<IClusterRoleBinding>(
        "rbac.authorization.k8s.io/v1",
        "ClusterRoleBinding",
      ),
      ClusterRoleBindingPatch: definePatch<IClusterRoleBinding>(
        "rbac.authorization.k8s.io/v1",
        "ClusterRoleBinding",
      ),
      Role: defineBuiltin<IRole>("rbac.authorization.k8s.io/v1", "Role"),
      RolePatch: definePatch<IRole>("rbac.authorization.k8s.io/v1", "Role"),
      RoleBinding: defineBuiltin<IRoleBinding>(
        "rbac.authorization.k8s.io/v1",
        "RoleBinding",
      ),
      RoleBindingPatch: definePatch<IRoleBinding>(
        "rbac.authorization.k8s.io/v1",
        "RoleBinding",
      ),
    },
  },
  autoscaling: {
    v2: {
      HorizontalPodAutoscaler: defineBuiltin<IHorizontalPodAutoscaler>(
        "autoscaling/v2",
        "HorizontalPodAutoscaler",
      ),
      HorizontalPodAutoscalerPatch: definePatch<IHorizontalPodAutoscaler>(
        "autoscaling/v2",
        "HorizontalPodAutoscaler",
      ),
    },
  },
  policy: {
    v1: {
      PodDisruptionBudget: defineBuiltin<IPodDisruptionBudget>(
        "policy/v1",
        "PodDisruptionBudget",
      ),
      PodDisruptionBudgetPatch: definePatch<IPodDisruptionBudget>(
        "policy/v1",
        "PodDisruptionBudget",
      ),
    },
  },
  storage: {
    v1: {
      CSIDriver: defineBuiltin<ICSIDriver>("storage.k8s.io/v1", "CSIDriver"),
      CSIDriverPatch: definePatch<ICSIDriver>("storage.k8s.io/v1", "CSIDriver"),
      CSINode: defineBuiltin<ICSINode>("storage.k8s.io/v1", "CSINode"),
      CSINodePatch: definePatch<ICSINode>("storage.k8s.io/v1", "CSINode"),
      CSIStorageCapacity: defineBuiltin<ICSIStorageCapacity>(
        "storage.k8s.io/v1",
        "CSIStorageCapacity",
      ),
      CSIStorageCapacityPatch: definePatch<ICSIStorageCapacity>(
        "storage.k8s.io/v1",
        "CSIStorageCapacity",
      ),
      StorageClass: defineBuiltin<IStorageClass>(
        "storage.k8s.io/v1",
        "StorageClass",
      ),
      StorageClassPatch: definePatch<IStorageClass>(
        "storage.k8s.io/v1",
        "StorageClass",
      ),
      VolumeAttachment: defineBuiltin<IVolumeAttachment>(
        "storage.k8s.io/v1",
        "VolumeAttachment",
      ),
      VolumeAttachmentPatch: definePatch<IVolumeAttachment>(
        "storage.k8s.io/v1",
        "VolumeAttachment",
      ),
      VolumeAttributesClass: defineBuiltin<IVolumeAttributesClass>(
        "storage.k8s.io/v1",
        "VolumeAttributesClass",
      ),
      VolumeAttributesClassPatch: definePatch<IVolumeAttributesClass>(
        "storage.k8s.io/v1",
        "VolumeAttributesClass",
      ),
    },
  },
  apiextensions: {
    v1: {
      CustomResourceDefinition: defineBuiltin<ICustomResourceDefinition>(
        "apiextensions.k8s.io/v1",
        "CustomResourceDefinition",
      ),
      CustomResourceDefinitionPatch: definePatch<ICustomResourceDefinition>(
        "apiextensions.k8s.io/v1",
        "CustomResourceDefinition",
      ),
    },
  },
} as const;

export const {
  core,
  apps,
  batch,
  networking,
  rbac,
  autoscaling,
  policy,
  storage,
  apiextensions,
} = api;
