import { createHash } from "node:crypto";
import console from "node:console";
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";
import { format } from "prettier";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const models = join(root, "..", "..", "node_modules", "kubernetes-models");
const groups = [
  ["core", "v1", "v1"],
  ["apps", "v1", "apps/v1"],
  ["batch", "v1", "batch/v1"],
  ["networking", "v1", "networking.k8s.io/v1"],
  ["rbac", "v1", "rbac.authorization.k8s.io/v1"],
  ["autoscaling", "v2", "autoscaling/v2"],
  ["policy", "v1", "policy/v1"],
  ["storage", "v1", "storage.k8s.io/v1"],
  ["apiextensions", "v1", "apiextensions.k8s.io/v1"],
];

// These are API operations, server diagnostics, or sensitive resources rather
// than declarative objects. Secret deliberately stays in the write-only add-on.
const excludedKinds = new Set([
  "Binding",
  "ComponentStatus",
  "Eviction",
  "Secret",
]);

const resources = [];
const digest = createHash("sha256");
for (const [namespace, version, directory] of groups) {
  for (const file of readdirSync(join(models, directory)).sort()) {
    if (!file.endsWith(".d.ts") || file === "index.d.ts") continue;
    const source = readFileSync(join(models, directory, file), "utf8");
    const interfaceMatch = source.match(
      /export interface I(\w+) extends TypeMeta/,
    );
    const apiVersionMatch = source.match(/"apiVersion": "([^"]+)"/);
    const kindMatch = source.match(/"kind": "([^"]+)"/);
    if (!interfaceMatch || !apiVersionMatch || !kindMatch) continue;
    const kind = kindMatch[1];
    if (kind.endsWith("List") || excludedKinds.has(kind)) continue;
    digest.update(`${directory}/${file}\0${source}\0`);
    resources.push({
      namespace,
      version,
      directory,
      interfaceName: `I${interfaceMatch[1]}`,
      apiVersion: apiVersionMatch[1],
      kind,
    });
  }
}

const imports = resources
  .map(
    ({ directory, interfaceName, kind }) =>
      `import type { ${interfaceName} } from "kubernetes-models/${directory}/${kind}";`,
  )
  .join("\n");

const namespaces = groups
  .map(([namespace, version]) => {
    const entries = resources
      .filter(
        (resource) =>
          resource.namespace === namespace && resource.version === version,
      )
      .map(
        ({ interfaceName, apiVersion, kind }) =>
          `      ${kind}: defineBuiltin<${interfaceName}>("${apiVersion}", "${kind}"),\n` +
          `      ${kind}Patch: definePatch<${interfaceName}>("${apiVersion}", "${kind}"),`,
      )
      .join("\n");
    return `  ${namespace}: {\n    ${version}: {\n${entries}\n    },\n  },`;
  })
  .join("\n");

const generated = `// Generated by scripts/generate.mjs from kubernetes-models. Do not edit.\n${imports}\nimport { defineBuiltin, definePatch } from "./resource.ts";\n\nexport const api = {\n${namespaces}\n} as const;\n\nexport const {\n${groups.map(([namespace]) => `  ${namespace},`).join("\n")}\n} = api;\n`;

const modelManifest = JSON.parse(
  readFileSync(join(models, "package.json"), "utf8"),
);
const lock = `${JSON.stringify(
  {
    source: "kubernetes-models",
    version: modelManifest.version,
    license: modelManifest.license,
    schemaDigest: `sha256:${digest.digest("hex")}`,
    groups: groups.map(([, , directory]) => directory),
    resources: resources.map(({ apiVersion, kind }) => ({ apiVersion, kind })),
  },
  null,
  2,
)}\n`;

const outputs = [
  [
    join(root, "src", "generated.ts"),
    await format(generated, { parser: "typescript" }),
  ],
  [join(root, "schema.lock.json"), lock],
];

if (process.argv.includes("--check")) {
  const stale = outputs
    .filter(([path, expected]) => {
      try {
        return readFileSync(path, "utf8") !== expected;
      } catch {
        return true;
      }
    })
    .map(([path]) => path);
  if (stale.length > 0) {
    throw new Error(
      `Generated Kubernetes API files are stale:\n${stale.join("\n")}\nRun npm run generate.`,
    );
  }
} else {
  for (const [path, contents] of outputs) writeFileSync(path, contents);
  console.log(`Generated ${String(resources.length)} Kubernetes resources.`);
}
